#!/usr/bin/env bash
set -euo pipefail

echo "🚀 SaaSPro — Deploy"
echo "====================="
echo ""
echo "  This project deploys to Vercel."
echo ""
echo "  Steps:"
echo "    1. Push to main branch (triggers CI)"
echo "    2. CI runs lint + build checks"
echo "    3. Vercel auto-deploys from main"
echo ""
echo "  Prerequisites:"
echo "    - Vercel project linked: vercel link"
echo "    - Environment variables set in Vercel dashboard"
echo "    - Neon PostgreSQL database provisioned"
echo ""
echo "  Manual deploy:"
echo "    cd apps/web && npx vercel --prod"
echo ""
echo "  Linked repo:"
echo "    git remote add origin <repo-url>"
echo "    git push -u origin main"
